"""Add Source.report_existing column

Revision ID: 4a3fcb9f0264
Revises: cca6a9a340ff
Create Date: 2024-04-23 02:53:09.582961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3fcb9f0264'
down_revision = 'cca6a9a340ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_existing', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('report_existing')

    # ### end Alembic commands ###
