"""Add Source.schedule_correction column

Revision ID: 6d5f6660c71b
Revises: 9e86225b96ca
Create Date: 2022-03-20 21:14:35.328822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d5f6660c71b"
down_revision = "9e86225b96ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column(
            "schedule_correction",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "schedule_correction")
    # ### end Alembic commands ###
