"""Add Source.announcement column

Revision ID: cca6a9a340ff
Revises: 386f6fe473a2
Create Date: 2023-09-13 00:06:40.813215

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cca6a9a340ff"
down_revision = "386f6fe473a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "announcement",
                sa.Boolean(),
                server_default="0",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_column("announcement")

    # ### end Alembic commands ###
