"""Add Source.version column

Revision ID: cfd3bf8c5ca3
Revises: 6d5f6660c71b
Create Date: 2022-08-29 16:41:02.540228

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Integer, column, table

# revision identifiers, used by Alembic.
revision = "cfd3bf8c5ca3"
down_revision = "6d5f6660c71b"
branch_labels = None
depends_on = None


sources = table("sources", column("version", Integer))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
    )
    op.execute(sources.update().values(version=2))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "version")
    # ### end Alembic commands ###
